### ISSUE TITLE
Cannot log in

### ISSUE THREAD

**Issue by phunni** [MCMrARM/Google-Play-API#12]
Am trying to download the x86 version of MCPE to use with MCPE Launcher, but everytime I run gplaydl and enter my credentials I get:

> http response body: Error=BadAuthentication

I've tried using my normal password and an app specific password, but nothing works for me...

**Comment by MCMrARM** [comment]
Use the `apk-download` branch from mcpelauncher, I integrated gplaydl there and implemented a browser based auth.

**Comment by phunni** [comment]
Brilliant - thank you. I'll give that a go.

**Comment by phunni** [comment]
Compile fails with:

`CMake Error at CMakeLists.txt:34 (add_subdirectory):
  The source directory

    /home/paul/tmp/mcpelauncher-linux/gplay_api

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:35 (set_target_properties):
  set_target_properties Can not find target to add properties to: gplaydl
`

**Comment by MCMrARM** [comment]
Clone recursively, also, wrong project.
