### ISSUE TITLE
Split configuration support

### ISSUE THREAD

**Issue by meme** [MCMrARM/Google-Play-API#16]
I'm fuzzy on the intricate details, but on some apps the natives are not supplied in the actual `base.apk`, but rather in split configs, like the following (for x86): `split_config.x86.apk`, etc. as well as ones for `hidpi`.

It'd be nice if Google-Play-API supported these and allowed you to select certain ones (or just download them all).

This issue seems to be relevant: https://github.com/yeriomin/play-store-api/issues/30.

I'm willing to take on this issue in the event no-one else can, but not at the moment.

**Comment by jpstotz** [comment]
The Java based APK downloader "Raccoon4" (also Apache license) has split download support: https://github.com/onyxbits/raccoon4

There you can see how it works.
