### ISSUE TITLE
How to set config so that I can download APKs for on my phone?

### ISSUE THREAD

**Issue by s5bug** [MCMrARM/Google-Play-API#17]
I'd like to be enrolled in the Minecraft beta so I can get beta APKs for MCPELauncher, but then I also want to download aarch64 APKs so that I can run both the beta and stable versions on my phone (to connect to servers). What do I have to put and where do I have to put it so that I can do this?

**Comment by MCMrARM** [comment]
https://mrarm.io/u/Paste%202019-05-11%2022-18-46.txt I think this answers your question?

**Comment by bugoverfl0w** [comment]
Hello how can I get master token, thanks :)
