### ISSUE TITLE
Linking fails

### ISSUE THREAD

**Issue by guppy42** [MCMrARM/Google-Play-API#5]
On Ubuntu 16.04 you will need;

sudo apt-get install libcurl4-gnutls-dev protobuf-compiler

The cmake version required is 3.6 and ubuntu 16.04 LTS only comes with 3.5 - you can change the required version in CMakeLists.txt

With the above changes it compiles but dies at 2% linking gplaydl with a whole ton of undefined references;
http://paste.ubuntu.com/23708256/

I can't determine if the errors are related to having the wrong cmake version, but it would be good to be able to compile it on Ubuntu LTS with out having to force update packages

**Comment by TheBrokenRail** [comment]
I manually installed cmake 3.6 on lubuntu 16.04 LTS and it worked.

**Comment by guppy42** [comment]
Confirmed - for Ubuntu 16.04 users;

You can get a new enough cmake with out breaking your system by doing a manual compile;

```
wget "https://cmake.org/files/v3.7/cmake-3.7.1.tar.gz"
tar xvzf cmake-3.7.1.tar.gz 
cd cmake-3.7.1/
./bootstrap 
make

```

now go to where ever you cloned Goole-Play-API and type

```
(path to where you extracted cmake)/bin/cmake .
make

```

and that compiles & links
