### ISSUE TITLE
API still working?

### ISSUE THREAD

**Issue by IMAN4K** [MCMrARM/Google-Play-API#7]
Thanks for the good job.
Does your API still working?

**Comment by inxomnyaa** [comment]
Looks like no. The auth options all don't work. Always "http response body: Error=BadAuthentication
Failed to login using the specified credentials: No auth cookie field returned", though everything is correct

**Comment by TheBrokenRail** [comment]
The API gives me the same error 
```bash
http response body: Error=BadAuthentication Failed to login using the specified credentials: No auth cookie field returned
```
@MCMrARM

**Comment by MCMrARM** [comment]
Yeah, can confirm.

**Comment by MCMrARM** [comment]
It might be necessary to implement a browser based login.
